import { useState, useEffect } from "react"
import { Button } from "./ui/button"
import { Input } from "./ui/input"
import { Label } from "./ui/label"
import { Textarea } from "./ui/textarea"
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "./ui/dialog"
import { Rule } from "../types"

interface DuplicateRuleModalProps {
  isOpen: boolean
  onClose: () => void
  onDuplicate: (ruleData: Partial<Rule>) => void
  rule: Rule | null
}

export function DuplicateRuleModal({ isOpen, onClose, onDuplicate, rule }: DuplicateRuleModalProps) {
  const [ruleName, setRuleName] = useState("")
  const [ruleDescription, setRuleDescription] = useState("")
  const [isDuplicating, setIsDuplicating] = useState(false)

  const handleDuplicate = async () => {
    if (!ruleName.trim() || !rule) {
      return
    }

    setIsDuplicating(true)
    
    try {
      // Create a duplicate with the new name and description
      const duplicatedRule: Partial<Rule> = {
        ...rule,
        name: ruleName.trim(),
        description: ruleDescription.trim(),
        status: 'draft', // New duplicated rules start as draft
        // Remove id and dates - these will be generated by the parent component
        id: undefined,
        createdAt: undefined,
        updatedAt: undefined,
        isFavorite: false, // Reset favorite status
        relatedEventsCount: 0 // Reset events count
      }
      
      onDuplicate(duplicatedRule)
      onClose()
    } catch (error) {
      console.error('Error duplicating rule:', error)
    } finally {
      setIsDuplicating(false)
    }
  }

  const handleClose = () => {
    setRuleName("")
    setRuleDescription("")
    onClose()
  }

  // Set default values when rule changes
  useEffect(() => {
    if (rule && isOpen) {
      setRuleName(`Copia de ${rule.name}`)
      setRuleDescription(rule.description || "")
    }
  }, [rule, isOpen])

  return (
    <Dialog open={isOpen} onOpenChange={handleClose}>
      <DialogContent className="sm:max-w-[425px]">
        <DialogHeader>
          <DialogTitle className="text-[16px]">Duplicar regla</DialogTitle>
          <DialogDescription className="text-[14px] text-muted-foreground">
            Crea una copia de la regla con un nuevo nombre.
          </DialogDescription>
        </DialogHeader>
        
        <div className="grid gap-4 py-4">
          <div className="grid gap-2">
            <Label htmlFor="duplicate-rule-name" className="text-[14px]">
              Nombre de la nueva regla *
            </Label>
            <Input
              id="duplicate-rule-name"
              value={ruleName}
              onChange={(e) => setRuleName(e.target.value)}
              placeholder="Ingresa el nombre de la nueva regla"
              className="text-[14px]"
            />
          </div>
          
          <div className="grid gap-2">
            <Label htmlFor="duplicate-rule-description" className="text-[14px]">
              Descripción (opcional)
            </Label>
            <Textarea
              id="duplicate-rule-description"
              value={ruleDescription}
              onChange={(e) => setRuleDescription(e.target.value)}
              placeholder="Describe brevemente el propósito de esta regla"
              className="min-h-[80px] text-[14px]"
            />
          </div>
        </div>
        
        <DialogFooter>
          <Button 
            variant="ghost" 
            onClick={handleClose}
            disabled={isDuplicating}
            className="text-[14px] font-normal"
          >
            Cancelar
          </Button>
          <Button 
            onClick={handleDuplicate}
            disabled={!ruleName.trim() || isDuplicating}
            className="bg-blue-600 hover:bg-blue-700 text-white text-[14px]"
          >
            {isDuplicating ? "Duplicando..." : "Duplicar"}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}